name: stripe_example
description: Demonstrates how to use the stripe plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^1.3.0
  pay: ^1.0.1
  http: ^0.13.1
  stripe_checkout:
    path: ../packages/stripe_checkout/
  stripe_web:
    path: ../packages/stripe_web/
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: OtomanopeeOne
      fonts:
        - asset: fonts/OtomanopeeOne.ttf