name: stripe_example
description: Demonstrates how to use the stripe plugin.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^10.2.0
  flutter_stripe_web: ^5.1.0
  pay: ^3.1.0
  http: ^1.1.0
  font_awesome_flutter: ^10.6.0
  platform: ^3.0.0
  web: ^1.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: OtomanopeeOne
      fonts:
        - asset: fonts/OtomanopeeOne.ttf
