name: stripe_identity_web
description: Web implementation of Stripe Identity Verification (not supported)
version: 1.0.0
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe_identity

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  stripe_identity_platform_interface:
    path: ../stripe_identity_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: StripeIdentityWeb
        fileName: stripe_identity_web.dart
