name: stripe_platform_interface
description: A new Flutter project.
version: 0.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"


dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+2  
  build_runner: ^1.11.5
  json_serializable: ^4.1.0
  pedantic: ^1.11.0

flutter: