name: flutter_stripe_web
description: Stripe sdk for Flutter web platform.
version: 1.1.1
homepage: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.0.3
  stripe_platform_interface: ^3.2.0
  js: ^0.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebStripe
        fileName: flutter_stripe_web.dart

