name: flutter_stripe_web
description: Stripe sdk bindings for the Flutter web platform. This package contains the implementation of the platform interface for web.
version: 3.0.0
homepage: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.0.3
  stripe_platform_interface: ^9.0.1
  js: ^0.6.3
  stripe_js: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lints: ^2.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebStripe
        fileName: flutter_stripe_web.dart
