name: stripe_platform_interface
description: Platform interface for stripe sdk
version: 2.5.0+1
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ">=1.1.0 <3.0.0"
  json_annotation: ^4.4.0
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.9
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.6
  flutter_lints: ^1.0.3
