name: stripe_platform_interface
description: Platform interface for stripe sdk
version: 1.0.2
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+2  
  json_serializable: ^4.1.3
  pedantic: ^1.11.0