name: stripe_platform_interface
description: Platform interface for stripe sdk
version: 12.3.0
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  meta: ^1.10.0
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.7.1
  flutter_lints: ^6.0.0
