name: stripe_platform_interface
description: Platform interface for stripe sdk
version: 6.0.0
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.9
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  flutter_lints: ^2.0.1
