name: stripe_platform_interface
description: Platform interface for stripe sdk
version: 9.2.2
repository: https://github.com/flutter-stripe/flutter_stripe
homepage: https://pub.dev/packages/flutter_stripe

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.1
