name: stripe_js
description: Stripe.js bindings for dart. This package is used by Stripe web so that the Stripe js sdk can be invoked directly.
version: 2.0.1
homepage: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  js: ^0.6.3
  json_annotation: ^4.5.0

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  test: ^1.22.0
  
false_secrets:
  - /tests/**

