name: stripe_js
description: Stripe.js bindings for dart. This package is used by Stripe web so that the Stripe js sdk can be invoked directly.
version: 3.4.0
homepage: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  meta: ^1.0.0
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.3.5
  json_serializable: ^6.5.4
  test: ^1.22.0
  
false_secrets:
  - /tests/**

