name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 7.0.0
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: stripe_android
      ios:
        default_package: stripe_ios
      web:
        default_package: stripe_web

dependencies:
  flutter:
    sdk: flutter
  stripe_android: ^7.0.1
  stripe_ios: ^7.0.0
  stripe_platform_interface:
    git:
      url: 'https://github.com/stefanodefilippo/flutter_stripe.git'
      path: 'packages/stripe_platform_interface'
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
