name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 12.0.2
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: stripe_android
      ios:
        default_package: stripe_ios
      web:
        default_package: stripe_web

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  stripe_android: ^12.1.0
  stripe_ios: ^12.1.0
  stripe_platform_interface: ^12.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
