name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 2.2.0
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  stripe_android:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      ref: 26556a1bed0f215a978c24b7c91795c30e42efd9
      path: packages/stripe_android
  stripe_ios:
    path: ../stripe_ios
  stripe_platform_interface:
    git:
      url: git@github.com:flutter-stripe/flutter_stripe.git
      ref: 26556a1bed0f215a978c24b7c91795c30e42efd9
      path: packages/stripe_platform_interface
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3



