name: flutter_stripe
description: Flutter library for Stripe. Supports PaymentSheets, Apple & Google Pay, SCA, PSD2 and much more.
version: 9.0.0+1
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: stripe_android
      ios:
        default_package: stripe_ios
      web:
        default_package: stripe_web

dependencies:
  flutter:
    sdk: flutter
  stripe_android: ^9.0.0+1
  stripe_ios: ^9.0.0
  stripe_platform_interface: ^9.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
