name: flutter_stripe_identity
description: Flutter plugin for Stripe Identity Verification. Allows users to verify their identity using Stripe Identity.
version: 1.0.0
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: stripe_identity_android
      ios:
        default_package: stripe_identity_ios
      web:
        default_package: stripe_identity_web

dependencies:
  flutter:
    sdk: flutter
  stripe_identity_android:
    path: ../stripe_identity_android
  stripe_identity_ios:
    path: ../stripe_identity_ios
  stripe_identity_platform_interface:
    path: ../stripe_identity_platform_interface
  stripe_identity_web:
    path: ../stripe_identity_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
